# Generated by Django 4.2.2 on 2023-07-15 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+!#,~-%&*£', length=12, max_length=40, prefix='NBL_')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(max_length=10)),
                ('start_save', models.DateField(max_length=8)),
                ('save_by', models.DateField(max_length=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuser', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tuserprofile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-', length=12, max_length=40, prefix='NBL_')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('dob', models.DateField(max_length=8)),
                ('address', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=100)),
                ('purpose_of_loan', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Declined', 'Declined'), ('Paid', 'Paid')], max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('duration', models.DateField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
